services:
  db:
    image: mysql:8
    container_name: photoshare-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: photoshare
      MYSQL_USER: photoshare
      MYSQL_PASSWORD: photoshare
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./photoshare-backend/PhotoShare.sql:/docker-entrypoint-initdb.d/PhotoShare.sql:ro
    restart: always

  backend:
    build:
      context: ./photoshare-backend
      dockerfile: backend.Dockerfile
    container_name: photoshare-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/photoshare?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: photoshare
      SPRING_DATASOURCE_PASSWORD: photoshare
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: always

  frontend:
    build:
      context: ./photoshare-frontend
      dockerfile: frontend.Dockerfile
    container_name: photoshare-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: photoshare-phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: photoshare
      PMA_PASSWORD: photoshare
    ports:
      - "8081:80"
    depends_on:
      - db
    restart: always

volumes:
  db_data: